# Generated by Django 3.1.4 on 2021-06-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNumber', models.CharField(max_length=255, verbose_name='座位編號')),
            ],
        ),
    ]
