# Generated by Django 3.1.4 on 2021-06-13 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout', models.DateTimeField(auto_now_add=True, verbose_name='借用時間')),
                ('returned', models.DateTimeField(null=True, verbose_name='歸還時間')),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seat.seat')),
            ],
        ),
    ]
