# Generated by Django 3.0.5 on 2021-06-14 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20210614_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='reserve_date',
            field=models.DateField(default=datetime.date(2021, 6, 14), verbose_name='日期'),
            preserve_default=False,
        ),
    ]
