# Generated by Django 3.1.4 on 2021-06-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_log_reserve_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='i',
            field=models.BooleanField(null=True, verbose_name='repeat'),
        ),
    ]
