# Generated by Django 3.1.4 on 2021-06-20 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_stu_rep_rep'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stu_rep',
        ),
    ]
